### ISSUE TITLE
Check if Lock is in use (Indexer is updating right now) even when directly updating Index.

### ISSUE THREAD

**Issue by rliebi** [valantic/pimcore-elastica-bridge#51]
The Service should also be aware of possible locks so a soon to be bad index won't be updated. This way we could implement a messenger queue which waits with the update until the lock is available.

**Comment by limenet** [comment]
@rliebi could you please clarify what you mean by "directly updating index"? Are you referring to the updates performed by `ChangeListener`?

**Comment by rliebi** [comment]
I mean when updating with the `PropagateChanges` Class.
